### ISSUE TITLE
Dockerfile for docker image

### ISSUE THREAD

**Issue by jorgeSia** [eniac/Beldi#1]
Hello,

We want to extend the evaluation benchmark with additional scenarios. To the best of our understanding, the deployment and the corresponding scripts are running through the provided docker image. Thus it is necessary to include in the Beldi image the additional scenarios. 

But the Dockerfile for recreating the image is _**not**_ provided. Would it be possible to provide such a Dockerfile? 

Any other advice/instruction for extending the benchmark would be highly appreciated. 

Thank you for your time.

**Comment by Mellonta** [comment]
Hi,

Thanks for the interest. The container contains
1. aws-cli, aws command line tools
2. https://www.serverless.com, for easy deployment
3. python and go

Dockerfile (beldi directory path is different from the image on dockerhub, which is done via `docker commit`):

```
FROM ubuntu:20.04

RUN apt-get update && apt-get install -y curl git wget build-essential python3 python3-pip
RUN curl -o- -L https://slss.io/install | VERSION=1.80.0 bash
RUN export PATH="$HOME/.serverless/bin:$PATH" >> $HOME/.bashrc

RUN wget https://golang.org/dl/go1.14.7.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf go1.14.7.linux-amd64.tar.gz
ENV GOROOT=/usr/local/go
ENV GOPATH=$HOME/go
ENV PATH=$GOPATH/bin:$GOROOT/bin:$PATH

RUN apt-get install -y unzip
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.0.44.zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip
RUN ./aws/install

RUN echo "alias python=python3" >> $HOME/.bashrc

COPY . /beldi
WORKDIR /beldi

RUN pip3 install -r requirements.txt

CMD ["tail", "-f", "/dev/null"]
```

**Comment by jorgeSia** [comment]
Thanks for the reply!
