### ISSUE TITLE
Questions about Exactly-once Semantics

### ISSUE THREAD

**Issue by EricPyZhou** [eniac/Beldi#2]
Hello,

In the section 2.2 of the paper, the definition of exactly-once semantics seems to be that of idempotence. Is the exactly-once semantics here different from the one in message queue?

Thanks in advance.

**Comment by sga001** [comment]
No, the exactly-once semantics in Beldi are not the same as idempotence.

Idempotence means that if you perform one action, and then you perform it again, additional actions have no effect beyond those of the first action.

Idempotence is one possible mechanism to guarantee at-most once execution semantics.


Beldi guarantees exactly-once, which is a conjunction of at-most once and at-least once semantics. Idempotence says nothing about at-least once execution semantics.

**Comment by EricPyZhou** [comment]
> No, the exactly-once semantics in Beldi are not the same as idempotence.
> 
> Idempotence means that if you perform one action, and then you perform it again, additional actions have no effect beyond those of the first action.
> 
> Idempotence is one possible mechanism to guarantee at-most once execution semantics.
> 
> Beldi guarantees exactly-once, which is a conjunction of at-most once and at-least once semantics. Idempotence says nothing about at-least once execution semantics.

First of all, thanks for the reply. I do agree that exactly-once semantics has little to do with idempotence. Here is the content of the definition:
_Exactly-once semantics: Beldi should guarantee exactly-once
execution semantics in the presence of SSF or worker crash
failures. That is, even if an SSF crashes in the midst of its execution and is restarted by the provider an arbitrary number of
times, the resulting state must be equivalent to that produced
by an execution in which the SSF ran exactly once, from start
to finish, without crashing._
I would think that there is no re-delivery in exactly-once semantics. The reason why I think of idempotence is because of restarting multiple times in case of failure.

**Comment by sga001** [comment]
I think it is helpful to separate the guarantee from the mechanism. Beldi aims for exactly-once.

The mechanism Beldi uses to do that is: (1) retries + (2) making requests idempotent. (1) gives us at-least once, and (2) gives us at most once.

The sentence you are quoting from our paper seems to be mixing the two :). We could've been a little clearer.

But yes, Beldi uses a write-ahead log to avoid redoing work that has already been done. This makes requests idempotent, and therefore guarantee at most once semantics. We then have other SSFs (intent collectors I believe we called them), that are triggered periodically and re-execute any pending functions. This gives us at-least once semantics under the assumption that if you execute the function enough times, eventually it will complete. Note that Belid assumes the function is bug-free. You could imagine a function that has an infinite loop and never finishes. Not much we can do to guarantee at-least once there.

**Comment by EricPyZhou** [comment]
> I think it is helpful to separate the guarantee from the mechanism. Beldi aims for exactly-once.
> 
> The mechanism Beldi uses to do that is: (1) retries + (2) making requests idempotent. (1) gives us at-least once, and (2) gives us at most once.
> 
> The sentence you are quoting from our paper seems to be mixing the two :). We could've been a little clearer.
> 
> But yes, Beldi uses a write-ahead log to avoid redoing work that has already been done. This makes requests idempotent, and therefore guarantee at most once semantics.

I kinda get it. Using retries(at-least once guarantee) + idempotence achieved using write-ahead log provide a similar effect to exact-once guarantee, is that sort of correct?

**Comment by EricPyZhou** [comment]
> > I think it is helpful to separate the guarantee from the mechanism. Beldi aims for exactly-once.
> > 
> > The mechanism Beldi uses to do that is: (1) retries + (2) making requests idempotent. (1) gives us at-least once, and (2) gives us at most once.
> > 
> > The sentence you are quoting from our paper seems to be mixing the two :). We could've been a little clearer.
> > 
> > But yes, Beldi uses a write-ahead log to avoid redoing work that has already been done. This makes requests idempotent, and therefore guarantee at most once semantics.
> 
> I kinda get it. Using retries(at-least once guarantee) + idempotence achieved using write-ahead log kinda provides a similar effect to exact-once guarantee, is that sort of correct?

**Comment by sga001** [comment]
Yup.

**Comment by EricPyZhou** [comment]
Thanks for clarifying, will close the issue now.
